name: BuildAndTest
on: 
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
    build:
        uses: eed-web-application/react-ui-demo-deployment/.github/workflows/build-test.yml@main
        secrets: inherit

